spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:EMOJI
logging.level.org.springframework.cache: TRACE
management:
  endpoint.restart.enabled: true
  endpoints.web.exposure.include: "*"
